# Image recognization 

In [1]:
# call the model and test
from skimage import io,transform
import tensorflow as tf
import numpy as np

In [2]:
# the directory of data
path = './flower_photos/'
# the saved modle directory
model_path = './model/'
# the name of modle
model_name = 'CNN_model-4'

In [3]:
#test images
path1 = "daisy/5547758_eea9edfd54_n.jpg"
path2 = "roses/394990940_7af082cf8d_n.jpg"
path3 = "dandelion/7355522_b66e5d3078_m.jpg"
path4 = "tulips/10791227_7168491604.jpg"
path5 = "sunflowers/6953297_8576bf4ea3.jpg"

In [4]:
path1 = path+path1
path2 = path+path2
path3 = path+path3
path4 = path+path4
path5 = path+path5

In [5]:
flower_dict = {0:'dasiy',1:'dandelion',2:'roses',3:'sunflowers',4:'tulips'}
w=100
h=100
c=3

In [6]:
#read test image and resize the images
def read_one_image(path):
    img = io.imread(path)
    img = transform.resize(img,(w,h),mode='constant')
    return np.asarray(img)

In [7]:
# prepare the data
data = []
data1 = read_one_image(path1)
data2 = read_one_image(path2)
data3 = read_one_image(path3)
data4 = read_one_image(path4)
data5 = read_one_image(path5)
data.append(data1)
data.append(data2)
data.append(data3)
data.append(data4)
data.append(data5)

/home/ma-user/anaconda3/envs/TensorFlow-1.13.1/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "


In [8]:
# start the session
with tf.Session() as sess:
    #latrest model path
    model_file=tf.train.latest_checkpoint(model_path)
    # import computive graph
    saver = tf.train.import_meta_graph(model_file+'.meta')
    # restore weight ingformation
    saver.restore(sess, model_file) 
    graph = tf.get_default_graph()
    # calculate the input nodes in graph
    x = graph.get_tensor_by_name("x:0")
    # feed information
    feed_dict = {x:data}
    # calculate the output nodes in graph
    logits = graph.get_tensor_by_name("logits_eval:0")
    # run the session
    classification_result = sess.run(logits,feed_dict)
    #diplay 4 decimals
    np.set_printoptions(precision=4, suppress=True)
    #print the prediction 
    print(classification_result)
    #print the maximum in the matrix
    print(tf.argmax(classification_result,1).eval())
    #Match category of flowers
    output = []
    output = tf.argmax(classification_result,1).eval()
    name=["fisrt","second","third","fourth","fifth"]
    for i in range(len(output)):
        print("The prediction of %s flower is:" %(name[i])+flower_dict[output[i]])

Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./model/CNN_model-4
[[0.0055 0.0024 0.0004 0.9838 0.0078]
 [0.     0.001  0.     0.     0.9989]
 [0.7593 0.0122 0.0258 0.2004 0.0024]
 [0.0003 0.5508 0.0075 0.0071 0.4343]
 [0.0002 0.0259 0.9736 0.0002 0.0002]]
[3 4 0 1 2]
The prediction of fisrt flower is:sunflowers
The prediction of second flower is:tulips
The prediction of third flower is:dasiy
The prediction of fourth flower is:dandelion
The prediction of fifth flower is:roses
