In [1]:
import tensorflow as tf 

In [2]:
# version
tf.__version__

'2.3.1'

In [3]:
# tensorflow 2.0
import tensorflow.compat.v1 as tf

# 1. constant

## 1.1 define a scalar constant

In [8]:
hello = tf.constant("hello,word") # step1 graph with 1 node 

In [9]:
hello

In [10]:
sess=tf.Session()               # step 2 :start a session 

In [13]:
print(sess.run(hello).decode())          # step 3:fetch result

RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

In [24]:
sess.close()                   # step 4 :close the session

In [25]:
# type('Hello, TensorFlow!')

In [26]:
# type(tf.constant('Hello, TensorFlow!'))

In [27]:
# type(tf.Session().run(tf.constant('Hello, TensorFlow!')))

## 1.2 define a matrix constant

In [ ]:
a=tf.constant([[2,3],[1,2]],name="matrix_1")

In [ ]:
a

In [ ]:
sess= tf.Session()
sess.run(a)

In [ ]:
sess.close()

# 2. addition/minus/multiply/devide

In [3]:
a = tf.constant(11)
b = tf.constant(10)

In [4]:
# d=a*b
c = a*b

In [5]:
c1= tf.multiply(a,b)

In [6]:
d = a+b

In [7]:
d1 = tf.add(a,b)

In [8]:
with tf.Session() as sess: #context management 
    print(sess.run(c))
    print(sess.run(c1))
    print(sess.run(d))
    print(sess.run(d1))

110
110
21
21


# 3. matrix_multiply

## 3.1 matrix multiply

In [9]:
m1 = tf.constant([[3,3],[2,2]])  # 2 x 2 matrix
m2 = tf.constant([[3,3],[1,1]])  # 2 x 2 matrix

In [10]:
m = tf.matmul(m1,m2)  # mat :matrix mul:mutiply

In [11]:
with tf.Session() as sess:
    print(sess.run(m))

[[12 12]
 [ 8  8]]


## 3.2 elementwise multiply

In [12]:
m_elementwise = tf.multiply(m1,m2)

In [13]:
with tf.Session() as sess:
    print(sess.run(m_elementwise))

[[9 9]
 [2 2]]


In [14]:
# shape
print(m.shape)
print(m_elementwise.shape)

(2, 2)
(2, 2)


# 4. Variables

## 4.1 define a variable

weights and bias are defined as variables at deep learning

### 4.1.1 naive definition with given initialize value

In [15]:
# 1. naive definition
var_1 = tf.Variable(3)

Instructions for updating:
Colocations handled automatically by placer.


In [16]:
var_1

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

### 4.1.2 definition with name and type

In [17]:
# definition with name and type
var_2 = tf.Variable([[3,2],],name="var2",dtype="int32") 
# this is an operator , the name is operator's name
# the name for the tensor is var:0

# node : operation ,output sereval tensors ,the orders of 0,1,2,3,....
# edge :data(tensor)

In [18]:
var_2

<tf.Variable 'var2:0' shape=(1, 2) dtype=int32_ref>

### 4.1.3 definition with random initialize function and shape

tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

tf.zeros(shape, dtype=tf.float32, name=None)

tf.zeros_like(tensor, dtype=None, name=None)

tf.ones(shape, dtype=tf.float32, name=None)

tf.ones_like(tensor, dtype=None, name=None)
......

In [19]:
var_3 =tf.Variable(tf.random_normal(shape=[2,3],stddev=1),name="var3",dtype=tf.float32)

In [20]:
var_3

<tf.Variable 'var3:0' shape=(2, 3) dtype=float32_ref>

In [21]:
var_4 = tf.Variable(tf.ones_like(var_3),name="var4")

In [22]:
var_4

<tf.Variable 'var4:0' shape=(2, 3) dtype=float32_ref>

In [23]:
init_op = tf.global_variables_initializer() # initialize operation
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(var_4))

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
var_3 = tf.Variable(tf.random_normal(shape=[2,3],stddev=1),name="var3",dtype=tf.float32)

In [25]:
var_3

<tf.Variable 'var3_1:0' shape=(2, 3) dtype=float32_ref>

In [26]:
var_4 = tf.Variable(tf.zeros_like(var_3,dtype=tf.int32),name="var4",dtype=tf.int32)

In [27]:
var_4

<tf.Variable 'var4_1:0' shape=(2, 3) dtype=int32_ref>

## 4.2 fecth the value of variables  
1. initialize operations
2. fetch multiple outputs 
3. notice on the naming trick

In [28]:
# how to get multiple output in one sess.run
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op) # run this initialize operation first
    var3_,var4_ = sess.run([var_3,var_4]) # how to run sereval output in one line
    print(var3_)
    print(var4_)

[[-1.0501342   1.3733529   0.06953499]
 [-0.201692    0.12825626 -0.1994014 ]]
[[0 0 0]
 [0 0 0]]


In [30]:
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op) # run this initialize operation first

    for i in range(1,4):
        var1_,var2_,var3_,var4_ = sess.run([var_1,var_2,var_3,var_4]) # run other operation
        print(var1_)
        print(var2_)
        print(var3_)

#     var_1,var_2,var_3,var_4 = sess.run([var_1,var_2,var_3])
#     print(var_1)
#     print(var_1)
#     print(var_3)
#     print(var_4)

3
[[3 2]]
[[-0.5159924  -1.1821338   0.07467844]
 [-1.314474    0.18531224  1.6866522 ]]


TypeError: Fetch argument 3 has invalid type <class 'numpy.int32'>, must be a string or Tensor. (Can not convert a int32 into a Tensor or Operation.)

# 5. placeholder / feed / fetch
1. definition of placeholder
2. the feed mechanism
3. the fecth mechanism

In [31]:
# x1 is the input 
# x2 is the input
# y is the output
# y = x1*x2

# define a graph 
x1 = tf.placeholder(shape=[1,1],dtype=tf.float32)
x2 = tf.placeholder(shape=[1,1],dtype=tf.float32)
y = tf.multiply(x1,x2) # x1 tensor and x2 is tensor

# start a session 
with tf.Session() as sess:
    y_ = sess.run(y,feed_dict={x1:[[1,],],x2:[[2,],]}) # feed & fecth
    print(y_)



[[2.]]


In [ ]:
# output=input1*input
input1 = tf.placeholder(tf.float32,shape=[3,2])  # shape of placeholder
input2 = tf.placeholder(tf.float32,shape=[3,2]) # shape of placeholder
output1 = tf.multiply(input1,input2)
with tf.Session() as sess:
    output = sess.run([output1],feed_dict={input1:[[1,2],[2,3],[1,1]],input2:[[1,2],[1,1],[3,1]]})
    print(output)

In [ ]:
# (b+c)*input
# b is a constant
# c is a constant 
# output = (b+c)*input

In [ ]:
# (b+c)*input
input3 = tf.placeholder(tf.int32)
b=tf.constant(2)
c=tf.constant(3)
tmp = tf.add(b,c)
out_1=tf.multiply(input3,tmp)

with tf.Session()  as sess:
    result = sess.run([out_1,tmp],feed_dict={input3:4})
    print(result)

# 6. model save & restore

1. save model
2. restore model structure
3. restore model variable
4. check the tensor name in graph 
5. check the variable name and value in graph

## 6.1. save model

In [1]:
import tensorflow as tf

In [2]:
# step1 construct a grpah y = var * x   
# step2 open a session and run the graph
# step3 save the graph and varibale

# step1:construct a graph
x = tf.placeholder(dtype=tf.int32)
var_6 = tf.Variable(3,dtype=tf.int32)

y = tf.multiply(x,var_6)

# initilize operation 
init_op = tf.global_variables_initializer()

# construct as saver 
saver = tf.train.Saver() 
# 1.save the graph structure
# 2.save the variable in the graph(session) 

# step2 : start a session
with tf.Session() as sess:
    sess.run(init_op) 
    y_ = sess.run(y,feed_dict={x:3}) # feed & fecth
    saver.save(sess,"./model/testmodel.ckpt") # save graph struture and variable 
    print(y_)

Instructions for updating:
Colocations handled automatically by placer.
9


## 6.2. restore model
1. restore the graph structure
2. check the tensor name
3. check the variable value and name 
4. feed and fecth

In [ ]:
# step1: restore the graph structure 
# step2: restore the variables 

In [3]:
# import tensorflow as tf
# step1: restore the graph structure
tf.reset_default_graph() # clear the existing node and edge 
saver = tf.train.import_meta_graph("./model/testmodel.ckpt.meta") # restore the graph structure
g = tf.get_default_graph() # get default graph 

In [4]:
# check the tensor name in restored graph 
for tensor_name in tf.contrib.graph_editor.get_tensors(g):
    print(tensor_name)


For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Tensor("Placeholder:0", dtype=int32)
Tensor("Variable/initial_value:0", shape=(), dtype=int32)
Tensor("Variable:0", shape=(), dtype=int32_ref)
Tensor("Variable/Assign:0", shape=(), dtype=int32_ref)
Tensor("Variable/read:0", shape=(), dtype=int32)
Tensor("Mul:0", dtype=int32)
Tensor("save/filename/input:0", shape=(), dtype=string)
Tensor("save/filename:0", shape=(), dtype=string)
Tensor("save/Const:0", shape=(), dtype=string)
Tensor("save/SaveV2/tensor_names:0", shape=(1,), dtype=string)
Tensor("save/SaveV2/shape_and_slices:0", shape=(1,), dtype=string)
Tensor("save/control_dependency:0", shape=(), dtype=string)
Tensor("save/RestoreV2/tensor_names:0", shape=(1,), dtype=string, device=/device:CPU:0)
Tensor("save/RestoreV2/shape_and_slices:0", shape=(1,), d

In [5]:
# how to check the name of variable in checkpoint file 
with tf.Session() as sess:
    saver.restore(sess,"./model/testmodel.ckpt") # restore the variable  
    for variable_name in tf.global_variables():
        print(variable_name,sess.run(variable_name))

Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./model/testmodel.ckpt
<tf.Variable 'Variable:0' shape=() dtype=int32_ref> 3


In [5]:
# open a new session 
with tf.Session() as sess:
    # restor value of variable
    saver.restore(sess,"./model/testmodel.ckpt")
    # graph.get_tensor_by_name
    print(sess.run(g.get_tensor_by_name("Mul:0"),feed_dict={g.get_tensor_by_name("Placeholder:0"):9}))
#     print(sess.run([var_6,y],feed_dict={g.get_tensor_by_name("Placeholder:0"):9}))
    

Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./model/testmodel.ckpt
27


## model save can only save graph with variables 

In [1]:

import tensorflow as tf
# step1:construct a graph without any variable
x = tf.placeholder(dtype=tf.int32)
x1 = tf.constant(3,dtype=tf.int32)

y = x+x1

# define a saver
saver = tf.train.Saver()

# step2:open a session 
with tf.Session() as sess:
    sess.run(y,feed_dict={x:3})
    saver.save(sess,"./model/testmodel.ckpt")


ValueError: No variables to save